#######################################################################################
## Configuration file of the Cloud Execution Environment                              #
#######################################################################################
## - name shall be filled with the System name. An example value shall
##   be: testDC
## - ntpConfig.servers shall list one or more external NTP server IPs that
##   shall be used for time synchronization.
## - dnsConfig.externalDnsServers shall list one or more external DNS server
##   IPs that shall be used as external DNS servers.
---
version: R7A
name: GOLIBAS_CEE

ntpConfig:
  ## IP addresses of the upstream external NTP servers. Four NTP servers are recommended.
  servers:
    - 192.168.1.1
    - 10.13.4.1
    
  ## Inside the CEE infra cluster one NTP server is elected master when NTP orphan mode starts.
  ## The stratum of this CEE NTP server must be configured. It is an integer less than 16.
  ## Set it to N+2, where N is the highest stratum among all the configured external NTP servers.
  orphanModeStratum: 9

dnsConfig:
  # The domain name must not use UPPER case letters
  internalDomain: cee.tld
## Optional A Record and AAAA Record in case name lookup is needed
## for communication e.g. with external peers like EO.
#  aRecord:
#    - name: <TO.BE.FILLED>
#      ipv4Address: <TO.BE.FILLED>
#  aaaaRecord:
#    - name: <TO.BE.FILLED>
#      ipv6Address: <TO.BE.FILLED>
## Optional configuration of external DNS servers
#  externalDnsServers:
#    - <TO.BE.FILLED>
#    - <TO.BE.FILLED>

timezone: Europe/Moscow

legaltext:
  local: "Attention! Unauthorized local access is strictly prohibited!\n"
  remote: "\nAttention! Unauthorized remote access is strictly prohibited!\n\n"

hostCredentials:
  hostUsername: ceeinfra
  hostPassword: rootroot
  grubUsername: grubuser
  grubPassword: rootroot
...
