#######################################################################################
##  Configuration file with CEE TLS information                                   #
#######################################################################################
##
---
transportLayerSecurity:
  - name: openstack_internal_tls
    minVersion: TLSv1.2
#    extraOptions: <TO.BE.FILLED>
    ciphersuites: ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384
    certificateFilename: os_int.crt
    caCertificateFilename: ca_int.crt
  - name: openstack_external_tls
    minVersion: TLSv1.2
#    extraOptions: <TO.BE.FILLED>
    ciphersuites: ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384
    certificateFilename: os_ext.crt
    caCertificateFilename: ca_ext.crt
  - name: glance_internal_tls
    minVersion: TLSv1.2
#    extraOptions: <TO.BE.FILLED>
    ciphersuites: ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384
    certificateFilename: glance_int.crt
    caCertificateFilename: ca_int.crt
  - name: infra_internal_tls
    minVersion: TLSv1.2
#    extraOptions: <TO.BE.FILLED>
    ciphersuites: ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384
    certificateFilename: infra_int.crt
    caCertificateFilename: ca_int.crt
  - name: infra_external_tls
    minVersion: TLSv1.2
#    extraOptions: <TO.BE.FILLED>
    ciphersuites: ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384
    certificateFilename: infra_ext.crt
    caCertificateFilename: ca_ext.crt
  - name: lcm_internal_tls
    minVersion: TLSv1.2
#    extraOptions: <TO.BE.FILLED>
    ciphersuites: ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384
    certificateFilename: lcm_int.crt
    caCertificateFilename: ca_int.crt
  - name: lcm_external_tls
    minVersion: TLSv1.2
#    extraOptions: <TO.BE.FILLED>
    ciphersuites: ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384
    certificateFilename: lcm_ext.crt
    caCertificateFilename: ca_ext.crt
  - name: serviceassurance_internal_tls
    minVersion: TLSv1.2
#    extraOptions: <TO.BE.FILLED>
    ciphersuites: ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384
    certificateFilename: sa_int.crt
    caCertificateFilename: ca_int.crt
  - name: serviceassurance_external_tls
    minVersion: TLSv1.2
#    extraOptions: <TO.BE.FILLED>
    ciphersuites: ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384
    certificateFilename: sa_ext.crt
    caCertificateFilename: ca_ext.crt
  - name: sdnc_nbi_tls
    minVersion: TLSv1.2
#    extraOptions: <TO.BE.FILLED>
    ciphersuites: ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384
    certificateFilename: sdnc_nbi.crt
    caCertificateFilename: ca_sdn.crt
  - name: sdnc_sbi_tls
    minVersion: TLSv1.2
#    extraOptions: <TO.BE.FILLED>
    ciphersuites: ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384
    certificateFilename: sdnc_sbi.crt
    caCertificateFilename: ca_sdn.crt
  - name: vxsds_internal_tls
    minVersion: TLSv1.2
#    extraOptions: <TO.BE.FILLED>
    ciphersuites: ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384
    certificateFilename: vxsds_int.crt
    caCertificateFilename: ca_int.crt
  - name: sdi_agent_tls
    minVersion: TLSv1.2
#    extraOptions: <TO.BE.FILLED>
    ciphersuites: ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384
    certificateFilename: sdi_agent.crt
    caCertificateFilename: ca_sdi.crt
  - name: internal_pki_tls
    minVersion: TLSv1.2
#    extraOptions: <TO.BE.FILLED>
    ciphersuites: ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384
    certificateFilename: auto
    caCertificateFilename: auto
...
